name: Github Pages Deploy

on:
  push:
    branches:
      - master

    strategy:
      matrix:
        node-version: [15.x]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          access-token: ${{ secrets.QSEC }}
          deploy-branch: gh-pages
